// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-Q1YJsrCz4R5PPa3oyA4FhHATrwz82Us',
    appId: '1:305891112971:web:03700a7bd8e3deaf3daf0e',
    messagingSenderId: '305891112971',
    projectId: 'messaging-bc9fc',
    authDomain: 'messaging-bc9fc.firebaseapp.com',
    storageBucket: 'messaging-bc9fc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFbbHCGoGCWeQeu1ngxY33mssN057Kais',
    appId: '1:305891112971:android:511542fbe07439af3daf0e',
    messagingSenderId: '305891112971',
    projectId: 'messaging-bc9fc',
    storageBucket: 'messaging-bc9fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_fA9gzivf6qWijHV5MP77dx7fdc8wQb0',
    appId: '1:305891112971:ios:03d4bd82d017e4543daf0e',
    messagingSenderId: '305891112971',
    projectId: 'messaging-bc9fc',
    storageBucket: 'messaging-bc9fc.appspot.com',
    androidClientId: '305891112971-f5b5381gk1nvlor4sbeaa7v72t8795g3.apps.googleusercontent.com',
    iosClientId: '305891112971-2uvgs1d8063384tlnm9q64a1nnpaooc6.apps.googleusercontent.com',
    iosBundleId: 'com.example.messaging',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_fA9gzivf6qWijHV5MP77dx7fdc8wQb0',
    appId: '1:305891112971:ios:03d4bd82d017e4543daf0e',
    messagingSenderId: '305891112971',
    projectId: 'messaging-bc9fc',
    storageBucket: 'messaging-bc9fc.appspot.com',
    androidClientId: '305891112971-f5b5381gk1nvlor4sbeaa7v72t8795g3.apps.googleusercontent.com',
    iosClientId: '305891112971-2uvgs1d8063384tlnm9q64a1nnpaooc6.apps.googleusercontent.com',
    iosBundleId: 'com.example.messaging',
  );
}
